apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: cluster-backend:v1
        ports:
        - containerPort: 1997
        env:
        - name: MONGODB_URL
          value: mongodb://root:example@mongodb:27017/todo?authSource=admin
